openapi: 3.0.3
info:
    title: ○○関連API
    version: 1.0.0
    description: |
        taskに関するエンドポイントです。

        - 一覧取得（GET /api/teams/:id/tasks）
        - 作成（POST /api/○○s）
        - 詳細取得（GET /api/○○s/:id）
        - 更新（PUT /api/○○s/:id, PATCH /api/○○s/:id）
        - 削除（DELETE /api/○○s/:id）

paths:
    /api/teams/:id/tasks:
        get:
            summary: タスク一覧取得
            description: チームに登録されているタスクの一覧を取得します。
            responses:
                "200":
                    description: 成功時のレスポンス
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: object
                                    properties:
                                        id:
                                            type: integer
                                            example: 1
                                            description: ○○ID
                                        name:
                                            type: string
                                            example: example_name
                                            description: ○○名
                            example:
                                - id: 1
                                  name: example_name_1
                                - id: 2
                                  name: example_name_2
                "400":
                    description: 不正なリクエスト

        post:
            summary: ○○作成
            description: 新しい○○を作成します。
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                name:
                                    type: string
                                    description: ○○名
                            required:
                                - name
            responses:
                "201":
                    description: 作成成功
                "400":
                    description: 不正なリクエスト

    /api/○○s/{id}:
        get:
            summary: ○○詳細取得
            description: 指定された○○IDの情報を取得します。
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: integer
                  description: ○○ID
            responses:
                "200":
                    description: 成功時
                "404":
                    description: 該当する○○が見つかりません

        put:
            summary: ○○全体更新（PUT）
            description: 指定された○○IDの情報を**全体的に更新**します。
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: integer
                  description: ○○ID
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                name:
                                    type: string
                                    description: ○○名（必須）
                            required:
                                - name
            responses:
                "200":
                    description: 更新成功
                "400":
                    description: 不正なリクエスト
                "404":
                    description: 該当する○○が見つかりません

        patch:
            summary: ○○部分更新（PATCH）
            description: 指定された○○IDの情報を**一部のみ更新**します。
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: integer
                  description: ○○ID
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                name:
                                    type: string
                                    description: ○○名（部分更新用）
                            # required: なし 部分更新なので任意
            responses:
                "200":
                    description: 更新成功
                "400":
                    description: 不正なリクエスト
                "404":
                    description: 該当する○○が見つかりません

        delete:
            summary: ○○削除
            description: 指定された○○IDのデータを削除します。
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                      type: integer
                  description: ○○ID
            responses:
                "204":
                    description: 削除成功（レスポンスなし）
                "404":
                    description: 該当する○○が見つかりません
