openapi: 3.0.3
info:
    title: チーム一覧取得 API
    version: 1.0.0
    description: |
        ## 基本情報

        - API論理名：チーム一覧取得
        - エンドポイント：http://localhost:3000/api/teams
        - メソッド：GET
        - 概要：登録されている全チームの基本情報を一覧で取得します。

        ## リクエスト

        - クエリパラメータ：
          なし

        - リクエストボディ：
          なし

        - リクエストサンプル：
          http://localhost:3000/api/teams/

        ## レスポンス

        - 成功時（200 OK）：

          | パラメータ名 | 型 | 説明         |
          |--------------|-----|--------------|
          | id           | int | チームID     |
          | name         | string | チーム名   |
          | owner_id     | int | オーナーID   |

        - レスポンスサンプル：

          ```json
          [
            {
              "id": 3,
              "name": "team_hashimoto",
              "owner_id": 3
            },
            {
              "id": 10,
              "name": "test_team",
              "owner_id": 1
            }
          ]
          ```

        ## エラーハンドリング

        | ステータスコード | 説明           | エラーメッセージ例          |
        |------------------|----------------|-----------------------------|
        | 例：400          | 不正なリクエスト | パラメータが不正です。     |

        ## 備考

        - 認証要件：[認証が必要かどうか、認証方式等を記載]
        - レート制限：[APIの呼び出し制限がある場合は記載]
        - その他注意事項：[その他、APIの使用に関する注意事項等を記載]

paths:
    /api/teams:
        get:
            summary: チーム一覧取得
            description: 登録されている全チームの基本情報を一覧で取得します。
            responses:
                "200":
                    description: 成功時のレスポンス
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: object
                                    properties:
                                        id:
                                            type: integer
                                            example: 3
                                            description: チームID
                                        name:
                                            type: string
                                            example: team_hashimoto
                                            description: チーム名
                                        owner_id:
                                            type: integer
                                            example: 1
                                            description: オーナーID
                            example:
                                - id: 3
                                  name: team_hashimoto
                                  owner_id: 3
                                - id: 10
                                  name: test_team
                                  owner_id: 1
                "400":
                    description: 不正なリクエスト
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                            example:
                                message: パラメータが不正です。
